### ISSUE TITLE
Mac App Store link doesn't seem to work

### ISSUE THREAD

**Issue by kitgrose** [warrenbuckley/Compact-Log-Format-Viewer#81]
I'm in Australia, and when clicking the Mac App Store button for the app, I get the attached error:

![Mac App Store error dialog reading "App Not Available: This app is currently not available in your country or region"](https://user-images.githubusercontent.com/165977/89871506-dcbe7e00-dbfa-11ea-8d1b-34ff28ee6f85.png)

I assumed this was simply an issue with the app in Australia, so I searched for the app in other stores (the US and UK) using [fnd](https://fnd.io/#/us/search?mediaType=all&term=compact%20log%20viewer), where it is similarly not found.

I'm happy to build the app myself as a workaround, but I'd much rather get updates through the store if possible.

**Comment by warrenbuckley** [comment]
I think the metrics for the MacOS usage was little & I don't currently build/release any other Apple apps, so my Apple Developer subscription lapsed. I assumed the application would still be available to download but that I would not be able to push any new updates. However it seems Apple just removes the listing :(

For now I recommend you build it manually. In future I may do auto-updates via GitHub releases instead of app stores.
